# Generated by Django 5.2.1 on 2025-05-29 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('duration_in_hours', models.IntegerField(default=2)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
